### ISSUE TITLE
ToHTML.HC.Z

### ISSUE THREAD

**Issue by ctrlcctrlv** [dseller/DolDoc.NET#4]
Cool project.

I wonder why not piggyback off of [`ToHTML.HC.Z`](https://templeos.holyc.xyz/Wb/Demo/ToHtmlToTXTDemo/ToHtml.html#l1)?

I think that TempleOS' implementation itself is the best arbiter of what DolDocs are valid or invalid, and any reimplementation won't be "bug-for-bug", so it's possible DD.NET can produce DolDocs not able to be understood by TOS itself.

Unfortunately I can't help much on source code side as I don't know anything about .NET. But I have considered these same problems. I think you are coming at it from the wrong end. I'd start with a _transpiler_ (and indeed have tried) from HolyC to C++. Then parsing DolDocs is as simple as using Terry (PBUH)'s implementation.

**Comment by dseller** [comment]
Hi @ctrlcctrlv ,

Thanks for taking the time to write this issue. 

It is not possible to write a completely compatible implementation of DolDoc outside of TempleOS without recreating a big chunk of TempleOS's runtime environment with it. TempleOS's DolDoc implementation is incredibly intertwined with its inner workings. I've been thinking of writing a HolyC compiler/interpreter, which would fix a lot of problems, but wouldn't be enough for full compatibility. In the end I decided that is something I don't want to do, and I am leaving it out of scope.

DolDoc.NET aims to be as compatible as possible, and it can display pretty much all DolDoc documents that are included in a TempleOS distro. More complex DolDocs can not be rendered, at least not the original. In my reimplementation, I have decided to implement my own runtime for providing user input, etc. For example, there is a form system included in DolDoc.NET that uses .NET reflection to generate forms and provide callbacks upon user interaction. (See https://github.com/dseller/DolDoc.NET/blob/master/Examples/DolDoc.Examples.TodoList/Program.cs) There's probably also a scripting language coming, but I'm still thinking about it.

Also, `ToHTML.HC.Z` is a very simple and basic converter that does not render most of the functions of DolDoc.

Thanks again!
